# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MM
email: contact@doctrineofdiscovery.org
description: >- # this means to ignore newlines until "baseurl:"
  "Papal Bulls of the 15th century gave Christian explorers the right to claim lands they "discovered" and lay claim to those lands for their Christian Monarchs. Any land that was not inhabited by Christians was available to be "discovered", claimed, and exploited."
twitter_username: indigenousVI
#github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Indigenous Values Initiative"
  avatar           : "/assets/images/indigenousvalues.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "The Indigenous Values Initiative is dedicated to articulating, disseminating and promoting values expressed by the leadership of the Onondaga Nation, the Central Fire (or Capital) of the Haudenosaunee Confederacy (made up of the Seneca, Tuscarora, Cayuga, Onondaga, Oneida and Mohawk nations)."
  location         : "Onondaga Nation Territory"
  #email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
        url: mailto:info@indigenousvalues.org
    - label: "Website"
      icon: "fas fa-fw fa-link"
        url: "https://indigenousvalues.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/indigenousVI"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
        url: "https://facebook.com/indigenousvalues"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
        url: "https://instagram.com/indigenousVI"
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
        url: https://twitter.com/indigenousVI
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
       url: https://facebook.com/indigenousvalues
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
        url: https://instagram.com/indigenousVI


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
