# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: Doctrine of Discovery
title_separator: "-"
email: contact@doctrineofdiscovery.org
description: >- # this means to ignore newlines until "baseurl:"
  "Papal Bulls of the 15th century gave Christian explorers the right to claim lands they "discovered" and lay claim to those lands for their Christian Monarchs. Any land that was not inhabited by Christians was available to be "discovered", claimed, and exploited."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doctrineofdiscovery.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: indigenousVI
#github_username: username
# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
search: true
teaser: "/assets/images/Mission-Interior-from-Lookout.jpg"
logo: /assets/images/doctrineofdiscovery_logo_new-88x88.png
breadcrumbs: true # true, false (default)
words_per_minute: 200

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-96037973-2"
    anonymize_ip: false # default

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: true #set incremental to true to speed things up. if changes arent showing set to false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Outputting
permalink: /:categories/:title/
paginate: 15 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site settings
atom_feed:
  path:

include:
  - _pages
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-minifier

author:
  name   : "Indigenous Values Initiative"
  avatar : "/assets/images/indigenousvalues-2020.png"
  bio    : "The Indigenous Values Initiative is dedicated to articulating, disseminating and promoting values expressed by the leadership of the Onondaga Nation, the Central Fire of the Haudenosaunee Confederacy."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://indigenousvalues.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/indigenousVI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/indigenousvalues"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://instagram.com/indigenousvalues"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/doctrineofdiscovery"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://youtube.com/c/IndigenousValuesInitiative"
image:
  path: /assets/images/Mission-Interior-from-Lookout.jpg
  width: 1080
  alt: Twitter Logo

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/indigenousVI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/indigenousvalues/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/indigenousvalues"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/doctrineofdiscovery"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://youtube.com/c/IndigenousValuesInitiative"

collections:
  authors:
    output: true
    permalink: /authors/:name

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      suggestedcitiation: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      suggestedcitiation: false
  # assets
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/pdfs"
    values:
      pdf: true
  # _author
  - scope:
      path: "_authors"
      type: authors
    values:
      layout: author-single
      author_profile: true
      suggestedcitiation: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

github: true

# Flags to enable/disable "donate box" alerts on lessons
donation_alerts: true


jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)