# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: Doctrine of Discovery
title_separator: "-"
email: contact@doctrineofdiscovery.org
description: >- # this means to ignore newlines until "baseurl:"
  "Papal Bulls of the 15th century gave Christian explorers the right to claim lands they "discovered" and lay claim to those lands for their Christian Monarchs. Any land that was not inhabited by Christians was available to be "discovered", claimed, and exploited."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stl3.theological.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: indigenousVI
#github_username: username
minimal_mistakes_skin: default
search: true
teaser: "/assets/images/onondaga-lake-east-shoreline-1.jpg"
logo: "/assets/images/compass.svg"
breadcrumbs: true # true, false (default)
words_per_minute: 200

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Site settings
atom_feed:
  path: atom.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Indigenous Values Initiative"
  avatar : "/assets/images/indigenousvalues.png"
  bio    : "The Indigenous Values Initiative is dedicated to articulating, disseminating and promoting values expressed by the leadership of the Onondaga Nation, the Central Fire of the Haudenosaunee Confederacy."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://indigenousvalues.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/indigenousVI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/indigenousVI"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://instagram.com/indigenousvalues"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/indigenousVI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/indigenousvalues"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
